# Generated by Django 5.2.1 on 2025-07-10 22:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_roadmap'),
    ]

    operations = [
        migrations.AddField(
            model_name='roadmap',
            name='progress',
            field=models.FloatField(default=0.0),
        ),
        migrations.CreateModel(
            name='Week',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('order', models.PositiveIntegerField()),
                ('milestone', models.BooleanField(default=False)),
                ('progress', models.FloatField(default=0.0)),
                ('roadmap', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='weeks', to='app.roadmap')),
            ],
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('resource_link', models.URLField()),
                ('duration', models.PositiveIntegerField(help_text='Duration in minutes')),
                ('type', models.CharField(choices=[('ARTICLE', 'Article'), ('PRACTISE', 'Practise')], max_length=10)),
                ('completed', models.BooleanField(default=False)),
                ('week', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='app.week')),
            ],
        ),
    ]
